@startuml
:Cam: --> (передать изображения)
(передать изображения) --> :Server:
:Server: --> (хранить данные)
:Server: --> (рассчет вектора движения облаков)
:Server: --> (рассчет времени до перекрытия солнца)
:Server: --> (включить двигатель)
:Server: --> (выключить двигатель)
:Server: --> (определение положения солнца)
(включить двигатель) --> :Engine:
(выключить двигатель) --> :Engine:
@enduml
